package com.creapolis.solennix.feature.inventory

import java.util.Locale

internal object InventoryStrings {
    private val isEnglish: Boolean
        get() = Locale.getDefault().language.startsWith("en")

    val title: String get() = if (isEnglish) "Inventory" else "Inventario"
    val detailTitle: String get() = if (isEnglish) "Inventory Detail" else "Detalle de Inventario"
    val formTitle: String get() = if (isEnglish) "Inventory Item" else "Item de Inventario"
    val adjustStock: String get() = if (isEnglish) "Adjust Stock" else "Ajustar Stock"
    fun currentStockWithUnit(name: String, stock: Double, unit: String): String = "$name — ${formatNumber(stock)} $unit"
    val quantityAdjustHint: String get() = if (isEnglish) "Quantity (+ adds, − subtracts)" else "Cantidad (+ suma, − resta)"
    val confirm: String get() = if (isEnglish) "Confirm" else "Confirmar"
    val lowStock: String get() = if (isEnglish) "Low stock" else "Stock bajo"
    val searchPlaceholder: String get() = if (isEnglish) "Filter inventory by name..." else "Filtrar inventario por nombre..."
    val sortName: String get() = if (isEnglish) "Name" else "Nombre"
    val sortStock: String get() = if (isEnglish) "Stock" else "Stock"
    val sortMinimum: String get() = if (isEnglish) "Minimum" else "Mínimo"
    val sortCost: String get() = if (isEnglish) "Cost" else "Costo"
    val emptyFiltered: String get() = if (isEnglish) "No results for current filter" else "Sin resultados para el filtro"
    val emptyInventory: String get() = if (isEnglish) "No inventory" else "Sin inventario"
    val ingredients: String get() = if (isEnglish) "Consumables" else "Consumibles"
    val supplies: String get() = if (isEnglish) "Per-event supplies" else "Insumos por Evento"
    val equipment: String get() = if (isEnglish) "Equipment" else "Equipos"
    fun stockLabel(stock: Double, unit: String): String = if (isEnglish) "Stock: ${formatNumber(stock)} $unit" else "Stock: ${formatNumber(stock)} $unit"
    val lowBadge: String get() = if (isEnglish) "Low" else "Bajo"
    val viewDetails: String get() = if (isEnglish) "View details" else "Ver Detalles"
    val menuEdit: String get() = if (isEnglish) "Edit" else "Editar"
    val menuDelete: String get() = if (isEnglish) "Delete" else "Eliminar"
    val menuAdjustStock: String get() = if (isEnglish) "Adjust stock" else "Ajustar Stock"
    val deleteItemTitle: String get() = if (isEnglish) "Delete item" else "Eliminar Item"
    val deleteItemMessage: String get() = if (isEnglish) "Are you sure you want to delete this inventory item? This action cannot be undone." else "¿Estás seguro de que deseas eliminar este item del inventario? Esta acción no se puede deshacer."
    val detailTypeEquipment: String get() = if (isEnglish) "Asset / Equipment" else "Activo / Equipo"
    val detailTypeSupply: String get() = if (isEnglish) "Per-event Supply" else "Insumo por Evento"
    val detailTypeIngredient: String get() = if (isEnglish) "Consumable Supply" else "Insumo Consumible"
    val currentStock: String get() = if (isEnglish) "Current Stock" else "Stock Actual"
    val belowMinimum: String get() = if (isEnglish) "Below minimum" else "Bajo mínimo"
    val minimumStock: String get() = if (isEnglish) "Minimum Stock" else "Stock Mínimo"
    val unitCost: String get() = if (isEnglish) "Unit Cost" else "Costo Unitario"
    fun perUnit(unit: String): String = if (isEnglish) "per $unit" else "por $unit"
    val stockValue: String get() = if (isEnglish) "Stock Value" else "Valor en Stock"
    val totalValue: String get() = if (isEnglish) "total value" else "valor total"
    val critical7Days: String get() = if (isEnglish) "Insufficient stock for the next 7 days!" else "¡Stock insuficiente para los próximos 7 días!"
    val belowMinAfterEvents: String get() = if (isEnglish) "Stock will fall below minimum after upcoming events" else "Stock quedará bajo el mínimo tras eventos próximos"
    val belowMinRecommended: String get() = if (isEnglish) "Stock is below the recommended minimum" else "Stock por debajo del mínimo recomendado"
    val enough7Days: String get() = if (isEnglish) "Enough stock for the next 7 days" else "Stock suficiente para los próximos 7 días"
    val noDemand7Days: String get() = if (isEnglish) "No demand in the next 7 days" else "Sin demanda en los próximos 7 días"
    val noUpcomingEvents: String get() = if (isEnglish) "No upcoming events" else "Sin eventos próximos"
    fun shortageMessage(demand: Double, stock: Double, shortage: Double, unit: String): String = if (isEnglish) "You need ${formatNumber(demand)} $unit in the next 7 days. You have ${formatNumber(stock)} $unit. Missing ${formatNumber(shortage)} $unit." else "Necesitas ${formatNumber(demand)} $unit en los próximos 7 días. Tienes ${formatNumber(stock)} $unit. Faltan ${formatNumber(shortage)} $unit."
    fun lowStockMessage(stock: Double, minimum: Double, unit: String): String = if (isEnglish) "Your current stock (${formatNumber(stock)} $unit) is below the recommended minimum (${formatNumber(minimum)} $unit)." else "Tu stock actual (${formatNumber(stock)} $unit) está por debajo del mínimo recomendado (${formatNumber(minimum)} $unit)."
    fun currentStockMessage(stock: Double, unit: String): String = if (isEnglish) "Current stock: ${formatNumber(stock)} $unit" else "Stock actual: ${formatNumber(stock)} $unit"
    val recommendedMinimum: String get() = if (isEnglish) "Recommended minimum" else "Mínimo Recomendado"
    val demandNext7Days: String get() = if (isEnglish) "Demand next 7 days" else "Demanda próximos 7 días"
    val demandByDate: String get() = if (isEnglish) "Demand by Date" else "Demanda por Fecha"
    val confirmedEvents: String get() = if (isEnglish) "Confirmed events" else "Eventos confirmados"
    val noConfirmedEventsUsingItem: String get() = if (isEnglish) "No confirmed events use this item." else "Sin eventos confirmados que usen este ítem."
    val today: String get() = if (isEnglish) "Today" else "Hoy"
    val tomorrow: String get() = if (isEnglish) "Tomorrow" else "Mañana"
    fun inDays(days: Int): String = if (isEnglish) "in $days days" else "en $days días"
    val totalDemand: String get() = if (isEnglish) "Total demand" else "Total demanda"
    val newStock: String get() = if (isEnglish) "New stock:" else "Nuevo stock:"
    val cancel: String get() = if (isEnglish) "Cancel" else "Cancelar"
    val save: String get() = if (isEnglish) "Save" else "Guardar"
    fun nearLimitMessage(remaining: Int): String = if (isEnglish) "You have $remaining inventory item(s) left in your plan." else "Te quedan $remaining ítem(s) de inventario disponibles en tu plan."
    fun limitReached(total: Int): String = if (isEnglish) "You have reached the limit of $total inventory items in your plan." else "Has alcanzado el límite de $total ítems de inventario en tu plan."
    fun loadItemError(message: String?): String = if (isEnglish) "Error loading item: ${message.orEmpty()}" else "Error al cargar item: ${message.orEmpty()}"
    fun saveItemError(message: String?): String = if (isEnglish) "Error saving item: ${message.orEmpty()}" else "Error al guardar item: ${message.orEmpty()}"
    val itemDeleted: String get() = if (isEnglish) "Item deleted" else "Item eliminado"
    val deleteItemFailed: String get() = if (isEnglish) "Could not delete the item" else "No se pudo borrar el item"
    val syncInventoryFailed: String get() = if (isEnglish) "Could not sync inventory. Showing cached data." else "No se pudo sincronizar el inventario. Mostrando datos en caché."
    fun adjustStockFailed(name: String): String = if (isEnglish) "Could not adjust stock for $name" else "No se pudo ajustar el stock de $name"
    val fallbackEvent: String get() = if (isEnglish) "Event" else "Evento"
    fun adjustStockError(message: String?): String = if (isEnglish) "Error adjusting stock: ${message.orEmpty()}" else "Error al ajustar stock: ${message.orEmpty()}"
    fun deleteError(message: String?): String = if (isEnglish) "Error deleting item: ${message.orEmpty()}" else "Error al eliminar item: ${message.orEmpty()}"
    val itemNameRequired: String get() = if (isEnglish) "Item Name *" else "Nombre del Item *"
    val typeRequired: String get() = if (isEnglish) "Type *" else "Tipo *"
    val ingredientType: String get() = if (isEnglish) "Ingredient" else "Ingrediente"
    val equipmentType: String get() = if (isEnglish) "Equipment" else "Equipo"
    val supplyType: String get() = if (isEnglish) "Supply" else "Insumo"
    val stockCurrentRequired: String get() = if (isEnglish) "Current Stock *" else "Stock Actual *"
    val stockMinimumRequired: String get() = if (isEnglish) "Minimum Stock *" else "Stock Mínimo *"
    val unitRequired: String get() = if (isEnglish) "Unit *" else "Unidad *"
    val unitCostOptional: String get() = if (isEnglish) "Unit Cost" else "Costo Unitario"
    val validationNameMin: String get() = if (isEnglish) "Name must be at least 2 characters" else "El nombre debe tener al menos 2 caracteres"
    val validationStockNegative: String get() = if (isEnglish) "Stock cannot be negative" else "El stock no puede ser negativo"
    val validationMinimumNegative: String get() = if (isEnglish) "Minimum stock cannot be negative" else "El stock mínimo no puede ser negativo"
    val validationUnitCostNegative: String get() = if (isEnglish) "Unit cost cannot be negative" else "El costo unitario no puede ser negativo"
    fun commonUnits(): List<String> = if (isEnglish) {
        listOf("piece", "kg", "g", "l", "ml", "box", "package")
    } else {
        listOf("pieza", "kg", "g", "l", "ml", "caja", "paquete")
    }

    private fun formatNumber(value: Double): String =
        if (value == value.toLong().toDouble()) value.toLong().toString() else String.format(Locale.US, "%.1f", value)
}
